import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const apiSource = readFileSync(new URL('../local-api.mjs', import.meta.url), 'utf8');

test('PRISM Agent keeps the newest dialogue at the bottom before every new option', () => {
  assert.match(appSource, /managerTranscript: ManagerTranscriptEntry\[\]/u);
  assert.match(appSource, /orderAgentTimeline<TimelineValue>/u);
  assert.match(appSource, /kind: "workflow", createdAt: currentContentUpdatedAt/u);
  assert.match(appSource, /kind: "manager", createdAt: entry\.createdAt/u);
  assert.match(appSource, /item\.value\.type === "workflow"/u);
  assert.match(appSource, /item\.value\.type === "manager"/u);
  assert.match(appSource, /aria-label="当前结果与选项"/u);
  assert.match(appSource, /aria-label="当前可执行选项"/u);
  assert.match(appSource, /createPortal\(content, host\)/u);
  assert.match(appSource, /<StageFinalActions className="storyboard-planning-actions">/u);
  assert.match(appSource, /<StageFinalActions className="direct-video-choice">/u);
  assert.match(appSource, /const agentScrollRef = useRef<HTMLDivElement \| null>\(null\)/u);
  assert.match(appSource, /ref=\{agentScrollRef\}/u);
  assert.doesNotMatch(appSource, /managerTurnsRef/u);
  assert.match(appSource, /useLayoutEffect\(\(\) => \{/u);
  assert.match(appSource, /container\.scrollTop = container\.scrollHeight/u);
  assert.match(appSource, /window\.setTimeout\(scrollToLatest, 120\)/u);
  assert.match(appSource, /\["manager", "workflow", "manager-status"\]/u);
  assert.match(appSource, /当前对话与操作/u);
  assert.match(appSource, /const agentActionSignature = \[/u);
  assert.match(appSource, /props\.agentTranscript\.length, props\.managerTranscript\.length/u);
  assert.match(styles, /\.manager-console \{[^}]*border:0;[^}]*border-radius:0;[^}]*background:transparent;/u);
  assert.match(styles, /\.manager-conversation-turn \{[^}]*width:94%;/u);
  assert.match(styles, /\.agent-action-tail > \.stage-final-confirmation \{ margin-top:0; \}/u);
  assert.match(appSource, /aria-label="PRISM Agent 诊断对话"/u);
  assert.match(appSource, /className="composer-context"><span>PRISM Agent<\/span><small>项目诊断<\/small>/u);
  assert.match(appSource, /aria-label="给PRISM Agent发消息" value=\{managerDraft\}/u);
  assert.match(appSource, /aria-label="这条回复的可执行操作"/u);
  assert.match(appSource, /command\.requiresConfirmation \? "确认并执行" : managerNavigationButtonLabel\(command\)/u);
  assert.match(appSource, /command\.kind === "regenerate_storyboard_image" \? "确认修复并重新生成"/u);
  assert.match(appSource, /className="manager-command-state running" role="status" aria-live="polite"/u);
  assert.match(appSource, /<b>正在执行<\/b>/u);
  assert.match(appSource, /<b>执行完成<\/b>/u);
  assert.match(appSource, /<b>执行未完成<\/b>/u);
  assert.match(styles, /@keyframes manager-command-spin/u);
  assert.match(styles, /prefers-reduced-motion:reduce[^}]*manager-command-state\.running/su);
  assert.match(appSource, /command\.stageId === "character-profiles"[^\n]*`\$\{prefix\}人物设定`/u);
  assert.match(appSource, /command\.stageId === "character-images"[^\n]*`\$\{prefix\}图片提示词`/u);
  assert.match(appSource, /onCancelManagerCommand/u);
  assert.match(appSource, /target\?\.kind === "video-prompt"[^}]*openVideoPrompt\(target\.id\)/su);
  assert.match(appSource, /target\?\.kind === "storyboard" && command\.stageId === "storyboard-prompts"[^}]*openStoryboardText\(target\.id\)/su);
  assert.match(appSource, /target\?\.kind === "character" && command\.stageId === "character-profiles"[^}]*openCharacterProfile\(target\.id\)/su);
  assert.match(appSource, /target\?\.kind === "character" && command\.stageId === "character-images"[^}]*openCharacterPrompt\(target\.id\)/su);
  assert.match(appSource, /status: "ready", completedAt, errorZh: "", resultZh: opened/u);
  assert.match(appSource, /command\.kind === "navigate" && <button className="manager-command-result-action"[\s\S]*?managerNavigationButtonLabel\(command, true\)/u);
  assert.match(appSource, /const updatedPrompts = await generateVideoPrompts\(\[targetId\], command.instructionZh \|\| command.summaryZh\)/u);
  assert.match(appSource, /openVideoPromptResult\(updatedPrompt\)/u);
  assert.match(appSource, /修改后的提示词已打开，可直接查看和继续编辑/u);
  assert.match(appSource, /function openProjectManagerCommandResult\(entryId: string, commandId: string\)/u);
  assert.match(appSource, /查看修改结果/u);
  assert.match(appSource, /角色更新后的下一步/u);
  assert.match(appSource, /保留更新，返回主线/u);
  assert.match(appSource, /检查并同步后续内容/u);
  assert.match(appSource, /function handleCharacterImageFollowUp/u);
  assert.match(appSource, /markVideoPromptsStale\(affectedSegmentKeys\)/u);
  assert.match(appSource, /setShotVideosApproval\("draft"\)/u);
  assert.match(appSource, /现有图片和视频均继续保留/u);
  assert.match(appSource, /onManagerFollowUp/u);
  assert.match(styles, /\.manager-command-followup/u);
  assert.match(apiSource, /followUpChoice: \['mainline', 'sync_downstream'\]/u);
  assert.match(appSource, /onOpenManagerCommandResult/u);
  assert.match(styles, /\.manager-command-result-action/u);
  assert.match(appSource, /aria-label="文字分镜"/u);
  assert.match(appSource, /updateStoryboardText\(storyboardTextEditorKey, storyboardTextEditorText\)/u);
  assert.match(appSource, /function restoreManagerCommandTargets\(entries: ManagerTranscriptEntry\[\]\)/u);
  assert.match(appSource, /restoreProjectManagerCommands\(entry\.turn, entry\.commands \|\| \[\]\)/u);
  assert.match(appSource, /projectManagerNavigationTarget\(command\.stageId, entry\.turn\?\.targetArtifacts \|\| \[\]\)/u);
  assert.match(appSource, /restoreManagerCommandTargets\(saved\.managerTranscript\)/u);
  assert.doesNotMatch(appSource, /entry\.turn\.proposedActions\.map/u);
  assert.doesNotMatch(appSource, /className="manager-input"/u);
  assert.doesNotMatch(appSource, /15 个环节全局视角/u);
  assert.doesNotMatch(appSource, /paid-action-note/u);
  assert.doesNotMatch(styles, /paid-action-note/u);
  assert.match(styles, /\.agent-scroll \.notice-box p \{[^}]*font-size:0 !important;/u);
  assert.match(styles, /\.notice-box p > strong \{[^}]*font-size:11px;/u);
  assert.match(styles, /\.notice-box p > br \{ display:none; \}/u);
  assert.doesNotMatch(appSource, /按每段已确认的文字分镜、结构化画格规划/u);
  assert.doesNotMatch(appSource, /总调用上限为/u);
  assert.doesNotMatch(appSource, /首轮\{missingRequestCount\}次文字API/u);
  assert.doesNotMatch(appSource, /最多2次文字API/u);
  assert.match(appSource, /managerMessageExecutionIntent\(normalized\)/u);
  assert.match(appSource, /executePreparedManagerCommands\(preparedEntry\.id, preparedCommands\)/u);
  assert.match(appSource, /executePreparedManagerCommands\(responseEntry\.id, executableCommands\)/u);
  assert.match(appSource, /executeManagerCommandWithFeedback/u);
  assert.match(appSource, /"retry_character_profiles"/u);
  assert.match(appSource, /"retry_storyboard_segments"/u);
  assert.match(appSource, /directStoryboardRepairRequested/u);
  assert.match(appSource, /正在修复文字分镜；仅处理未通过校验的文字内容/u);
  assert.match(appSource, /文字分镜已修复并写入/u);
  assert.match(appSource, /让 Agent 修复并写入文字分镜/u);
  assert.match(appSource, /const result = await startCharacterDesign\(\)/u);
  assert.match(appSource, /角色档案已重新整理并写入/u);
  assert.match(appSource, /managerTranscriptRef\.current = nextTranscript/u);
  assert.match(appSource, /已完成 \$\{completed\.length\} 项修改/u);
  assert.match(appSource, /function CharacterProfileModal/u);
  assert.match(appSource, /aria-label="人物设定"/u);
  assert.match(appSource, /年龄、外貌与体态 · 每行一项/u);
  assert.match(appSource, /保存人物设定/u);
  assert.match(appSource, /setCharacterApproval\("draft"\)/u);
  assert.match(appSource, /现有角色图片继续保留/u);
  assert.match(appSource, /command\.kind === "revise_character_design"/u);
  assert.match(appSource, /\/api\/characters\/revise-design/u);
  assert.match(appSource, /\/api\/props\/revise-design/u);
  assert.match(appSource, /command\.kind === "regenerate_prop_image"[\s\S]*candidate\.kind === "revise_prop_design"/u);
  assert.match(appSource, /openCharacterPromptResult\(body\.prompt\)/u);
  assert.match(appSource, /setCharacterApproval\("approved"\);[\s\S]*?setCharacterAssetsApproval\("draft"\);[\s\S]*?openCharacterPromptResult\(body\.prompt\)/u);
  assert.match(appSource, /修改后的人物设定与图片提示词已保存并打开/u);
  assert.match(appSource, /waitingForPromptRevision/u);
  assert.match(appSource, /等待前一项完成/u);
  assert.match(appSource, /查看修改结果/u);
  assert.match(apiSource, /runCharacterDesignRevision/u);
  assert.match(appSource, /character-stage-error/u);
  assert.match(appSource, /出错位置/u);
  assert.match(styles, /\.character-stage-error > p/u);
});

test('global manager API loads the saved project and never enters a mutation route', () => {
  assert.match(apiSource, /url\.pathname === '\/api\/project-manager\/turn'/u);
  assert.match(apiSource, /creativeSessions\.load\(\)/u);
  assert.match(apiSource, /buildProjectManagerContext\(session\)/u);
  assert.match(apiSource, /compileProjectManagerCommands\(turn, context\)/u);
  assert.doesNotMatch(apiSource, /WORKFLOW_STAGE_BY_MUTATION_ROUTE[^}]*project-manager/su);
});
